# Generated by Django 4.1 on 2024-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('state', models.IntegerField(db_index=True, default=-1)),
                ('createTime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('createUserId', models.CharField(max_length=255, null=True)),
                ('deletedTime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
