# Generated by Django 4.1 on 2024-03-11 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goview', '0003_project_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
