# Generated by Django 4.1 on 2024-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goview', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
